---
name: NovaPerms
version: 0.0.1-dev
main: MohamadRZ\NovaPerms\NovaPermsPlugin
api: 5.0.0
src-namespace-prefix: MohamadRZ\NovaPerms

commands:
  novaperms:
    permission: novaperms.use
    aliases:
      - np

permissions:
  novaperms.use:
    default: true

...
