---
name: NovaPerms
version: 0.0.1-dev
main: MohamadRZ\NovaPerms\NovaPermsPlugin
api: 5.0.0
src-namespace-prefix: MohamadRZ\NovaPerms

permissions:
  novaperms.use:
    default: true
  novaperms.help:
    default: op

...
