<?php

namespace MohamadRZ\NovaPerms\model;

use MohamadRZ\NovaPerms\node\Node;

class Group extends PermissionHolder
{
    public function __construct(private string $name)
    {
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setNode(Node $node): void
    {
        parent::setNode($node); // TODO: Change the autogenerated stub
        $this->updateUsersForGroup($this->getName());
    }

    public function unsetNode(Node $node): bool
    {
        $isRemoved = parent::unsetNode($node);

        if ($isRemoved) {
            $this->updateUsersForGroup($this->getName());
        }

        return $isRemoved;
    }

}
