########################################################################################
#                                   StellarRanks Config                                #
########################################################################################
#                                                                                        #
#              ____  _       _ _            ____             _                           #
#              / ___|| |_ ___| | | __ _ _ __|  _ \ __ _ _ __ | | _____                   #
#              \___ \| __/ _ \ | |/ _` | '__| |_) / _` | '_ \| |/ / __|                  #
#              ___) | ||  __/ | | (_| | |  |  _ < (_| | | | |   <\__ \                   #
#              |____/ \__\___|_|_|\__,_|_|  |_| \_\__,_|_| |_|_|\_\___/                  #
#                                                                                        #
#   ✨ StellarRanks: The Ultimate PocketMine-MP Rank & Permission System                 #
#                                                                                        #
#   Fast, clean, and inspired by LuckPerms. Manage groups, permissions, tracks, and      #
#   advanced server access with maximum flexibility.                                     #
#   Built for both single-server and powerful Minecraft networks!                        #
#                                                                                        #
#   👉 GitHub: https://github.com/MohamadRZ/StellarRanks                                 #
#                                                                                        #
#   📄 Below are expert settings to power-up your server. Every option is documented!    #
########################################################################################

# The default rank/group for new players and anyone who doesn't have a specific rank.
# (Examples: "guest", "default", "member")
default_rank: "guest"

# The main player identity method used for all data storage and API lookups.
# Recommended: "uuid" for best reliability & name-change safety!
# Options:
#   username  = player's username (not recommended for big/public servers)
#   uuid      = Universally Unique Identifier (recommended)
#   xuid      = Xbox Live user id (for cross-platform servers)
#   ip        = IP Address (not recommended except for rare custom setups)
primary_key: username
# ----------------------------------- !!! CRITICAL WARNING !!! ------------------------------------
# !!! Be extremely careful when changing this setting after initial setup. !!!
# !!! If you switch this AFTER players have data associated with the OLD key, !!!
# !!! your existing player data MIGHT BECOME CORRUPTED or LOST. !!!
# !!! It is STRONGLY RECOMMENDED to use "username" from the start, or perform a !!!
# !!! full data migration if you must switch keys later. !!!
# -------------------------------------------------------------------------------------------------

timing:
  # Enable or disable the built-in performance profiler for StellarRanks.
  # When enabled, collects and reports timing info for each operation!
  enabled: false

  # Any operation taking more than this many milliseconds is flagged as "slow".
  # (Example: 100.0 = anything over 100ms will be reported.)
  global_bad_threshold: 100.0

  # When exporting timing reports, automatically wipe/reset all timing data.
  # Helps keep memory usage low; turn off only if you want long-term analytics.
  auto_reset_after_export: true

  # How many timing results to keep in memory (per tracked method/task).
  # Bigger numbers = longer trend insight, but more RAM required!
  history_size: 100

########################################################################################
#                          StellarRanks: Elevate Your Server!                          #
#    - LuckPerms-like experience, 100% PHP, stunningly fast and super flexible.        #
#    - Real time analytics, context meta, tracks, cross-server support, and more!      #
#    - Clean code, full docs, Open Source, and always community-first!                 #
#    - Upgrade your Minecraft Pocket Edition experience now.                           #
########################################################################################
