<?php

namespace MohamadRZ\NovaPerms\storage\implementations\file;

class CombinedConfigurateStorage extends AbstractConfigurateStorage
{

    public function init(): void
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function shutdown(): void
    {
        parent::shutdown(); // TODO: Change the autogenerated stub
    }

    protected function readFile(StorageLocation $location, string $name): ?array
    {
        // TODO: Implement readFile() method.
    }

    protected function saveFile(StorageLocation $location, string $name, ?array $data): void
    {
        // TODO: Implement saveFile() method.
    }

    public function loadAllGroups(): void
    {
        // TODO: Implement loadAllGroups() method.
    }

    public function loadAllTracks(): void
    {
        // TODO: Implement loadAllTracks() method.
    }

}
