<?php

declare(strict_types=1);

namespace MohamadRZ\NovaPerms;

use MohamadRZ\NovaPerms\configs\ConfigManager;
use MohamadRZ\NovaPerms\model\GroupManager;
use MohamadRZ\NovaPerms\model\NodeManager;
use MohamadRZ\NovaPerms\model\UserManager;
use MohamadRZ\NovaPerms\storage\implementations\StorageImplementation;
use MohamadRZ\NovaPerms\storage\Storage;
use MohamadRZ\NovaPerms\storage\StorageFactory;
use MohamadRZ\NovaPerms\timings\Timings;
use MohamadRZ\NovaPerms\utils\ExecuteTimer;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;

class NovaPermsPlugin extends PluginBase {
    use SingletonTrait;

    private static string $datePath;
    private static ConfigManager $configManager;
    private static Timings $timings;
    private static NodeManager $permissionManager;
    private static UserManager $userManager;
    private static Storage $storage;
    private static GroupManager $groupManager;

    protected function onLoad(): void
    {
        self::setInstance($this);
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        $version = $this->getDescription()->getVersion();
        $softWareName = $this->getServer()->getName();
        $softVersion = $this->getServer()->getVersion();

        $logo = "
        
                §l§eNovaPerms §7| §bPermission System §8• §7v§a$version §r
                  §7running on §b$softWareName §8/ §7$softVersion
";

        $this->getServer()->getLogger()->info($logo);

        $timer = new ExecuteTimer();

        self::$datePath = $this->getDataFolder();
        self::$configManager = new ConfigManager(self::$datePath);
        self::$timings = new Timings(self::$datePath . "/timings/", self::$configManager);
        self::$storage = new Storage($this);

        self::$permissionManager = new NodeManager();
        self::$groupManager = new GroupManager();
        self::$userManager = new UserManager();

        $time = $timer->end();
        $this->getLogger()->info("§aSuccessfully enabled! §7(Took §b" . $time . "§7)");
        parent::onEnable();
    }


    public static function getInstance(): NovaPermsPlugin
    {
        return self::$instance;
    }

    public static function getDatePath(): string
    {
        return self::$datePath;
    }

    /**
     * @return ConfigManager
     */
    public static function getConfigManager(): ConfigManager
    {
        return self::$configManager;
    }

    /**
     * @return Timings
     */
    public static function getTimings(): Timings
    {
        return self::$timings;
    }

    /**
     * @return NodeManager
     */
    public static function getPermissionManager(): NodeManager
    {
        return self::$permissionManager;
    }

    /**
     * @return UserManager
     */
    public static function getUserManager(): UserManager
    {
        return self::$userManager;
    }

    /**
     * @return Storage
     */
    public static function getStorage(): Storage
    {
        return self::$storage;
    }

    /**
     * @return GroupManager
     */
    public static function getGroupManager(): GroupManager
    {
        return self::$groupManager;
    }
}
