<?php

declare(strict_types=1);

namespace MohamadRZ\StellarRanks;

use MohamadRZ\StellarRanks\configs\ConfigManager;
use MohamadRZ\StellarRanks\configs\PlayerConfig;
use MohamadRZ\StellarRanks\configs\RanksConfig;
use MohamadRZ\StellarRanks\timings\Timings;
use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;

class StellarRanks extends PluginBase {
    use SingletonTrait;

    private static string $datePath;
    private static PlayerConfig $playerConfig;
    private static RanksConfig $ranksConfig;
    private static ConfigManager $configManager;
    private static Timings $timings;

    protected function onLoad(): void
    {
        self::setInstance($this);
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        self::$datePath = $this->getDataFolder();
        self::$configManager = new ConfigManager(self::$datePath);
        self::$timings = new Timings(self::$datePath."/timings/", self::$configManager);
        self::$playerConfig = new PlayerConfig(self::$datePath);
        self::$ranksConfig = new RanksConfig(self::$datePath);

        $this->getScheduler()->scheduleRepeatingTask(new StellarTask(), 60);

        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public static function getInstance(): StellarRanks
    {
        return self::$instance;
    }

    public static function getDatePath(): string
    {
        return self::$datePath;
    }

    /**
     * @return PlayerConfig
     */
    public static function getPlayerConfig(): PlayerConfig
    {
        return self::$playerConfig;
    }

    /**
     * @return RanksConfig
     */
    public static function getRanksConfig(): RanksConfig
    {
        return self::$ranksConfig;
    }

    /**
     * @return ConfigManager
     */
    public static function getConfigManager(): ConfigManager
    {
        return self::$configManager;
    }

    /**
     * @return Timings
     */
    public static function getStellarTimings(): Timings
    {
        return self::$timings;
    }
}
